site_name: Documenta√ß√£o do Projeto
site_description: Documenta√ß√£o t√©cnica oficial
site_author: Isthmus Omni

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

nav:
  - In√≠cio: index.md
  - B2B.Dominio:
      - EmbalagemUtil: b2b-dominio/IsthmusWinthor.Nucleo/IsthmusWinthor.Dominio/EmbalagemUtil.md
      - MoneyExtensions: b2b-dominio/IsthmusWinthor.Nucleo/IsthmusWinthor.Dominio/MoneyExtensions.md 

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true

  # üëá necess√°rio para Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format

plugins:
  - search
  - mermaid2
