site_name: Documentação do Projeto
site_description: Documentação técnica oficial
site_author: Isthmus Omni

theme:
  name: material
  language: pt-BR
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Alternar modo claro/escuro
  features:
    - navigation.tabs
    - content.code.copy
    - search.highlight

nav:
  - Início: index.md
  - B2B.Dominio:
      - EmbalagemUtil: b2b-dominio/IsthmusWinthor.Nucleo/IsthmusWinthor.Dominio/EmbalagemUtil.md
      - MoneyExtensions: b2b-dominio/IsthmusWinthor.Nucleo/IsthmusWinthor.Dominio/MoneyExtensions.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences  # mermaid2 já registra automaticamente, não precisa de custom_fences

plugins:
  - search
  - mermaid2
