site_name: Isthmus Omni - Documentação Técnica - Fábrica
site_description: Documentação técnica destinada à fábrica de softwares da Isthmus Omni
site_author: Isthmus Omni

extra_css:
  - css/custom-colors.css

theme:
  name: material
  logo: img/logo.png
  language: pt-BR
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Alternar modo claro/escuro
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Alternar modo claro/escuro
  features:
    - navigation.tabs
    - content.code.copy
    - search.highlight

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - js/init-mermaid.js

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
